apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::410144913646:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-10ZMJZE5JVLFI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::410144913646:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-01T12:32:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1916"
  uid: 6df4a0a6-7904-4a8a-9419-32af01d647f8
